apiVersion: v1
kind: Service
metadata:
  name: backend-v2
  namespace: facedetect-3b3s
  labels:
    app: backend-v2
    service: backend-v2
spec:
  ports:
  - name: http #-backend
    port: 5001
    targetPort: http
    #protocol: TCP
  selector:
    app: backend-v2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v2
  namespace: facedetect-3b3s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-v2
  template:
    metadata:
      labels:
        app: backend-v2
    spec:
      imagePullSecrets:
        - name: gitlab-auth
      containers:
        - name:  backend-v2
          image: registry.gitlab.com/PATH_TO_REGISTRY/backend:3backends3storage
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5001
              #protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: NODE_SERVICE
              value: "backend-v2"
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: backend-v2-dstrule
  namespace: facedetect-3b3s
spec:
  host: backend-v2.facedetect-3b3s.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    loadBalancer:
      simple: RANDOM
    outlierDetection:
      consecutiveGatewayErrors: 5
      interval: 10s
      baseEjectionTime: 6m
---