apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: facedetect-3b3s
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 31115
    targetPort: http
    #protocol: TCP
    name: http
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: facedetect-3b3s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: gitlab-auth
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - backend-v1
                - backend-v2
                - backend-v3
                - storage-v1
                - storage-v2
                - storage-v3
            topologyKey: "kubernetes.io/hostname"
            namespaces:
              - facedetect-3b3s
      containers:
      - name:  frontend
        image: registry.gitlab.com/PATH_TO_REGISTRY/frontend:3backends3storage
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 5000
            #protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        env:
          - name: NODE_SERVICE
            value: "frontend"
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
---
